<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>14bd5229-7b85-4364-9a32-8898781ae5eb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Functions" Version="13.5.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChampionsDraft.Functions\ChampionsDraft.Functions.csproj" />
  </ItemGroup>

</Project>
